---
- hosts: localhost
  connection: chroot
  become_user: root
  become: yes
  gather_facts: yes
  # vars_files:
  #   - "vars/main.yml"

  tasks:
    - name: Update grub for Debian family
      command: grub-mkconfig -o /boot/grub/grub.cfg
      when:
        - ansible_os_family == "Debian"

    - name: Update grub for RedHat family
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when:
        - ansible_os_family == "RedHat"

    - name: Update initramfs for Debian family
      command: update-initramfs -u
      when:
        - ansible_os_family == "Debian"

    - name: Find latest initramfs for RedHat family
      shell: ls -1t /boot/initramfs-*.img | head -1
      register: found_file

    - name: Update initramfs for RedHat family
      command: "dracut -f -v {{ found_file.stdout_lines[0] }}"
      when:
        - ansible_os_family == "RedHat"

    - name: Check grub for Debian family
      command: "grub-install --recheck {{ new_disk }}"
      when:
        - ansible_os_family == "Debian"

    - name: Check grub for RedHat family
      command: "grub2-install --recheck {{ new_disk }}"
      when:
        - ansible_os_family == "RedHat"
