---
- hosts: chroot_instance
  connection: chroot
  user: root
  vars_files:
    - "vars/main.yml"

  tasks:
    - name: Touch .autorelabel for SELinux
      file:
        path: /.autorelabel
        state: touch
      when:
        - ansible_os_family == "RedHat"

    - name: Update grub for RedHat 6
      command: grubby --update-kernel=0 --args=rd.lvm.lv={{ vg_name }}/root
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Update grub CMDLINE_LINUX for RedHat 7 or newer family
      lineinfile:
        state: present
        dest: /etc/default/grub
        backrefs: yes
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.*rd\.lvm\.lv\=)\"[^\"]+)(\".*)'
        line: '\1 rd.lvm.lv={{ vg_name }}/root\2'
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

    - name: Update grub OS_PROBER for RedHat 8 family
      lineinfile:
        state: present
        dest: /etc/default/grub
        regexp: '^GRUB_DISABLE_OS_PROBER='
        line: GRUB_DISABLE_OS_PROBER=true
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: Generate grub config for Debian family
      command: grub-mkconfig -o /boot/grub/grub.cfg
      when:
        - ansible_os_family == "Debian"

    - name: Unset kernelopts for RedHat 8 family
      command: grub2-editenv - unset kernelopts
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

    - name: Generate grub config for RedHat 7 or newer family
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

    - name: Generate initramfs for Debian family
      command: update-initramfs -u
      when:
        - ansible_os_family == "Debian"

    # - name: Find latest initramfs for RedHat family
    #   find:
    #     paths: /boot
    #     patterns: '*.img'
    #     recurse: no
    #     file_type: file
    #     excludes: '*rescue*'
    #   register: found_file
    #   when:
    #     - ansible_os_family == "RedHat"

    # - name: Find latest initramfs for RedHat family
    #   shell: ls -1t /boot/initramfs-3.*64.img | head -1
    #   #shell: ls -1t /boot/initramfs-*.img | head -1
    #   register: found_file
    #   when:
    #     - ansible_os_family == "RedHat"

    - name: Generate initramfs for RedHat 6 family
      command: dracut -f -H
      #command: "dracut -f -H {{ found_file.stdout_lines[0] }}"
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Generate initramfs for RedHat 7 or newer family
      command: dracut -f -H --regenerate-all
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

    - name: Check grub for Debian family or RedHat 6 family
      command: "grub-install --recheck {{ new_disk }}"
      when:
        - ansible_os_family == "Debian" or ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: Check grub for RedHat 7 or newer family
      command: "grub2-install --recheck {{ new_disk }}"
      when:
        - ansible_os_family == "RedHat" and ansible_distribution_major_version >= "7"

    - name: Flush to disk
      command: "sync"
