---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  vars_files:
    - "vars/main.yml"
    - "vars/{{ ansible_os_family }}.yml"

  tasks:
    - name: Install dependencies
      package:
        state: latest
        name:
          - lvm2
          - rsync
          - parted

    - name: Erase root partition for amazon-chroot
      parted:
        device: "{{ new_disk }}"
        number: 1
        state: absent

    - name: Create a new boot partition
      parted:
        device: "{{ new_disk }}"
        number: 1
        flags: [ boot ]
        state: present
        part_type: primary
        part_end: "{{ boot_size }}MB"

    - name: Create a new root partition
      parted:
        device: "{{ new_disk }}"
        number: 2
        flags: [ lvm ]
        state: present
        part_type: primary
        part_start: "{{ boot_size|int + 1 }}MB"
        part_end: 100%

    - name: Create {{ vg_name }} volume group on top of {{ new_disk }}2
      lvg:
        vg: "{{ vg_name }}"
        pvs: "{{ new_disk }}2"
        pesize: "4" # 32 or 128K

    - name: Create logical volume swap of {{ swap_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: swap
        size: "{{ swap_size }}"
      when: create_swap

    - name: Create logical volume var of {{ var_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: var
        size: "{{ var_size }}"

    - name: Create logical volume log of {{ log_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: log
        size: "{{ log_size }}"

    - name: Create logical volume audit of {{ audit_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: audit
        size: "{{ audit_size }}"

    - name: Create logical volume home of {{ home_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: home
        size: "{{ home_size }}"

    - name: Create logical volume tmp of {{ tmp_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: tmp
        size: "{{ tmp_size }}"

    - name: Create logical volume root of {{ root_size }}
      lvol:
        vg: "{{ vg_name }}"
        lv: root
        size: "{{ root_size }}"

    - name: Create {{ boot_fs }} filesystem on {{ new_disk }}1
      filesystem:
        fstype: "{{ boot_fs }}"
        dev: "{{ new_disk }}1"
        #force: yes

    # - name: Create swap filesystem on /dev/mapper/{{ vg_name }}-swap
    #   filesystem:
    #     fstype: swap
    #     dev: "/dev/mapper/{{ vg_name }}-swap"
    #     #force: yes
    #   when: create_swap

    - name: Create swap filesystem on /dev/mapper/{{ vg_name }}-swap
      command: mkswap /dev/mapper/{{ vg_name }}-swap
      when: create_swap

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-var
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-var"
        #force: yes

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-log
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-log"
        #force: yes

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-audit
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-audit"
        #force: yes

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-home
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-home"
        #force: yes

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-tmp
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-tmp"
        #force: yes

    - name: Create {{ root_fs }} filesystem on /dev/mapper/{{ vg_name }}-root
      filesystem:
        fstype: "{{ root_fs }}"
        dev: "/dev/mapper/{{ vg_name }}-root"
        #force: yes

    - name: Create newroot dir
      file:
        path: /newroot
        state: directory
        mode: 0755

    - name: Remove any temp fstab files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - '/etc/fstab.fake'
        - '/etc/fstab.new'

    - name: Mount newroot dir
      mount:
        path: /newroot
        src: "/dev/mapper/{{ vg_name }}-root"
        fstype: "{{ root_fs }}"
        fstab: /etc/fstab.new
        state: mounted

    - name: Create boot dir
      file:
        path: /newroot/boot
        state: directory
        mode: 0755

    - name: Find boot UUID
      shell: blkid -o value -s UUID {{ new_disk }}1
      register: found_uuid

    - name: Mount boot dir
      mount:
        path: /newroot/boot
        src: UUID={{ found_uuid.stdout_lines[0] }}
        fstype: "{{ boot_fs }}"
        dump: 1
        passno: 2
        fstab: /etc/fstab.new
        state: mounted

    - name: Create var dir
      file:
        path: /newroot/var
        state: directory
        mode: 0755

    - name: Mount var dir
      mount:
        path: /newroot/var
        src: "/dev/mapper/{{ vg_name }}-var"
        fstype: "{{ root_fs }}"
        opts: nodev
        fstab: /etc/fstab.new
        state: mounted

    - name: Create log dir
      file:
        path: /newroot/var/log
        state: directory
        mode: 0755

    - name: Mount log dir
      mount:
        path: /newroot/var/log
        src: "/dev/mapper/{{ vg_name }}-log"
        fstype: "{{ root_fs }}"
        opts: nodev
        fstab: /etc/fstab.new
        state: mounted

    - name: Create audit dir
      file:
        path: /newroot/var/log/audit
        state: directory
        mode: 0755

    - name: Mount audit dir
      mount:
        path: /newroot/var/log/audit
        src: "/dev/mapper/{{ vg_name }}-audit"
        fstype: "{{ root_fs }}"
        opts: nodev
        fstab: /etc/fstab.new
        state: mounted

    - name: Create home dir
      file:
        path: /newroot/home
        state: directory
        mode: 0755

    - name: Mount home dir
      mount:
        path: /newroot/home
        src: "/dev/mapper/{{ vg_name }}-home"
        fstype: "{{ root_fs }}"
        opts: nodev
        fstab: /etc/fstab.new
        state: mounted

    - name: Create tmp dir
      file:
        path: /newroot/tmp
        state: directory
        mode: 0755

    - name: Mount tmp dir
      mount:
        path: /newroot/tmp
        src: "/dev/mapper/{{ vg_name }}-tmp"
        fstype: "{{ root_fs }}"
        opts: nodev,noexec,nosuid
        fstab: /etc/fstab.new
        state: mounted

    - name: Add swap dir
      mount:
        path: swap
        src: "/dev/mapper/{{ vg_name }}-swap"
        fstype: swap
        fstab: /etc/fstab.new
        state: present
      when: create_swap

    # - name: Create oldroot dir
    #   file:
    #     path: /oldroot
    #     state: directory
    #     mode: 0755
    #   when: not run_sync
    #
    # - name: Mount oldroot
    #   mount:
    #     path: /oldroot
    #     src: /
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted
    #   when: not run_sync
    #
    # - name: Rsync /oldroot to /newroot for Debian family
    #   synchronize:
    #     src: /oldroot/
    #     dest: /newroot/
    #     archive: yes
    #     rsync_opts:
    #       - "--exclude=swapfile"
    #       - "--exclude=/etc/fstab.*"
    #       - "--exclude=/home/ansible/ansible"
    #       - "--one-file-system"
    #   when:
    #     - ansible_os_family == "Debian"
    #     - not run_sync
    #
    # - name: Rsync /oldroot to /newroot for RedHat family
    #   synchronize:
    #     src: /oldroot/
    #     dest: /newroot/
    #     archive: yes
    #     rsync_opts:
    #       - "-A"
    #       - "-X"
    #       - "--exclude=/etc/fstab.*"
    #       - "--exclude=/home/ansible/ansible"
    #       - "--one-file-system"
    #   when:
    #     - ansible_os_family == "RedHat"
    #     - not run_sync
    #
    # - name: Update new /etc/fstab pass1
    #   replace:
    #     path: "/etc/fstab.new"
    #     regexp: "newroot"
    #
    # - name: Update new /etc/fstab pass2
    #   replace:
    #     path: "/etc/fstab.new"
    #     regexp: "//"
    #     replace: "/"
    #
    # - name: Copy new /etc/fstab to newroot
    #   copy:
    #     src: /etc/fstab.new
    #     dest: /newroot/etc/fstab
    #     owner: root
    #     group: root
    #     mode: '0644'
    #
    # - name: Edit default grub CMDLINE_LINUX for RedHat family
    #   lineinfile:
    #     state: present
    #     dest: /newroot/etc/default/grub
    #     backrefs: yes
    #     regexp: '^(GRUB_CMDLINE_LINUX=(?!.*rd\.lvm\.lv\=)\"[^\"]+)(\".*)'
    #     line: '\1 rd.lvm.lv={{ vg_name }}/root\2'
    #   when:
    #     - ansible_os_family == "RedHat"
    #
    # - name: Edit default grub OS_PROBER for RedHat 8 family
    #   lineinfile:
    #     state: present
    #     dest: /newroot/etc/default/grub
    #     path: /etc/selinux/config
    #     regexp: '^GRUB_DISABLE_OS_PROBER='
    #     line: GRUB_DISABLE_OS_PROBER=true
    #   when:
    #     - ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
    #
    # - name: Touch .autorelabel for SELinux
    #   file:
    #     path: /newroot/.autorelabel
    #     state: touch
    #   when:
    #     - ansible_os_family == "RedHat"
    #
    # - name: Mount proc on newroot
    #   mount:
    #     path: /newroot/proc
    #     src: /proc
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted
    #
    # - name: Mount dev on newroot
    #   mount:
    #     path: /newroot/dev
    #     src: /dev
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted
    #
    # - name: Mount sys on newroot
    #   mount:
    #     path: /newroot/sys
    #     src: /sys
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted

    # - name: Mount run on newroot
    #   mount:
    #     path: /newroot/run/lvm
    #     src: /run/lvm
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted
    #   when:
    #     - ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"
