---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  vars_files:
    - "vars/main.yml"
    - "vars/{{ ansible_os_family }}.yml"

  tasks:
    - name: Create oldroot dir
      file:
        path: /oldroot
        state: directory
        mode: 0755
      when: run_rsync

    - name: Mount oldroot
      mount:
        path: /oldroot
        src: /
        opts: bind
        fstype: none
        fstab: /etc/fstab.fake
        state: mounted
      when: run_rsync

    - name: Rsync /oldroot to /newroot for Debian family
      synchronize:
        src: /oldroot/
        dest: /newroot/
        archive: yes
        rsync_opts:
          - "--exclude=swapfile"
          - "--exclude=/etc/fstab.*"
          - "--exclude=/home/ansible/ansible"
          - "--one-file-system"
      when:
        - ansible_os_family == "Debian"
        - run_rsync

    - name: Rsync /oldroot to /newroot for RedHat family
      synchronize:
        src: /oldroot/
        dest: /newroot/
        archive: yes
        rsync_opts:
          - "-A"
          - "-X"
          - "--exclude=/etc/fstab.*"
          - "--exclude=/home/ansible/ansible"
          - "--one-file-system"
      when:
        - ansible_os_family == "RedHat"
        - run_rsync

    # - name: Mount proc on newroot
    #   mount:
    #     path: /newroot/proc
    #     src: /proc
    #     opts: bind
    #     fstype: none
    #     fstab: /etc/fstab.fake
    #     state: mounted

    - name: Mount proc on newroot
      command: mount --bind /proc /newroot/proc

    - name: Mount dev on newroot
      command: mount --bind /proc /newroot/dev

    - name: Mount sys on newroot
      command: mount --bind /proc /newroot/sys
