---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: no

  tasks:
  - name: Umount all bind mounts
    mount:
      path: "{{ item }}"
      opts: bind
      state: unmounted
    with_items:
      - '/newroot/proc/sys/fs/binfmt_misc'
      - '/newroot/proc'
      - '/newroot/dev/pts'
      - '/newroot/dev'
      - '/newroot/sys'
    #ignore_errors: yes
